# Generated by Django 4.2.24 on 2025-09-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de sesión")),
                ("active", models.BooleanField(default=False, verbose_name="Activa")),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_days",
                        to="gestion.grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de sesión",
                "verbose_name_plural": "Días de sesión",
                "unique_together": {("grupo", "fecha")},
            },
        ),
    ]
