# Generated by Django 4.2.24 on 2025-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_sessionday'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='exento_pago',
            field=models.BooleanField(default=False, verbose_name='Exento de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_transaccion',
            field=models.CharField(choices=[('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('DEPOSITO', 'Depósito Bancario'), ('EFECTIVO', 'Efectivo'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('PAYPAL', 'PayPal'), ('OTRO', 'Otro')], default='PAGO_MOVIL', help_text='Método usado para el pago', max_length=20, verbose_name='Tipo de transacción'),
        ),
    ]
