# Generated by assistant to make banco_emisor nullable
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_usuario_exento_pago_alter_pago_tipo_transaccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="banco_emisor",
            field=models.CharField(choices=[
                ("0001", "0001 - Banco Central de Venezuela"),
                ("0102", "0102 - Banco de Venezuela, S.A. Banco Universal"),
                ("0104", "0104 - Banco Venezolano de Cr\u00e9dito, S.A. Banco Universal"),
                ("0105", "0105 - Banco Mercantil C.A., Banco Universal"),
                ("0108", "0108 - Banco Provincial, S.A. Banco Universal"),
                ("0114", "0114 - Banco del Caribe C.A., Banco Universal"),
                ("0115", "0115 - Banco Exterior C.A., Banco Universal"),
                ("0128", "0128 - Banco Caron\u00ed C.A., Banco Universal"),
                ("0134", "0134 - Banesco Banco Universal, C.A."),
                ("0137", "0137 - Banco Sofitasa Banco Universal, C.A."),
                ("0138", "0138 - Banco Plaza, Banco Universal"),
                ("0146", "0146 - Banco de la Gente Emprendedora C.A."),
                ("0151", "0151 - Banco Fondo Com\u00fan, C.A Banco Universal"),
                ("0156", "0156 - 100% Banco, Banco Comercial, C.A"),
                ("0157", "0157 - DelSur, Banco Universal C.A."),
                ("0163", "0163 - Banco del Tesoro C.A., Banco Universal"),
                ("0166", "0166 - Banco Agr\u00edcola de Venezuela C.A., Banco Universal"),
                ("0168", "0168 - Bancrecer S.A., Banco Microfinanciero"),
                ("0169", "0169 - Mi Banco, Banco Microfinanciero, C.A."),
                ("0171", "0171 - Banco Activo C.A., Banco Universal"),
                ("0172", "0172 - Bancamiga Banco Universal, C.A."),
                ("0173", "0173 - Banco Internacional de Desarrollo C.A., Banco Universal"),
                ("0174", "0174 - Banplus Banco Universal, C.A."),
                ("0175", "0175 - Banco Bicentenario del Pueblo, Banco Universal C.A."),
                ("0177", "0177 - Banco de la Fuerza Armada Nacional Bolivariana, B.U."),
                ("0178", "0178 - N58 Banco Digital, Banco Microfinanciero"),
                ("0191", "0191 - Banco Nacional de Cr\u00e9dito C.A., Banco Universal"),
                ("0601", "0601 - Instituto Municipal de Cr\u00e9dito Popular"),
            ], max_length=4, null=True, blank=True, verbose_name="Banco emisor"),
        ),
    ]
